name: Build & Deploy Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4
      - name: 安装Node环境
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: 安装依赖
        run: npm install
      - name: 打包编译
        run: npm run build
      - name: 部署到Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
